[package]
name = "osm_api"
version = "0.1.0"
authors = ["Martin Marmsoler <martin.marmsoler@brainlab.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
url = {version = "2.2.2"}
xmltree = "0.10.3"
chrono = "0.4"
